# Numpy with Keith Galli

#### Load in NumPy library

In [7]:
import numpy as np

#### The basics

In [8]:
# Initialize array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
# Multidimensional array
b = np.array([[4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


In [10]:
# Dimension
print(a.ndim)
print(b.ndim)

# Shape
print(a.shape)
print(b.shape)

# Number of elements
print(a.size)
print(b.size)

1
2
(3,)
(2, 3)
3
6


In [11]:
# Data type
print(a.dtype)
print(b.dtype)

# Size of an element in memory
print(a.itemsize)
print(b.itemsize)

# Total memory size
print(a.nbytes)
print(b.nbytes)

int32
float64
4
8
12
48


#### Accesing / changing specific elements

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [13]:
# Get a specific element in [r, c]
print(a[1,5])
print(a[1,-2])

# Get a full row
print(a[0, :])

# Get a full column
print(a[:, 2])

13
13
[1 2 3 4 5 6 7]
[ 3 10]


In [14]:
# [startindex:endindex:stepsize]
print(a[0, 1:6:2])
print(a[0, 5:0:-2])

[2 4 6]
[6 4 2]


In [15]:
# Change single value
a[1,5] = 20
print(a)

# Change column
a[:,2] = 5
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
# With 3 dimensions
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)
print(b.shape)

print(b[0,1,1])
print(b[0, 0, :])

b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
4
[1 2]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


#### Initializing different types of arrays

In [17]:
# All zeros
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# All ones
print(np.ones(5))
print(np.ones((2,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# All other values
print(np.full(5, 99))

# Given shape of other array
print(np.full_like(b, 99))

[99 99 99 99 99]
[[[99 99]
  [99 99]]

 [[99 99]
  [99 99]]]


In [30]:
# Random numbers
print(np.random.rand(4,2))
print(np.random.randint(1, 10, size=(3,3)))

# Identity matrix
print(np.identity(5))

[[0.17153583 0.00411152]
 [0.49843961 0.14960885]
 [0.55265028 0.13708621]
 [0.1962396  0.01685333]]
[[5 3 5]
 [4 2 6]
 [4 9 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
# Repeat array
arr = np.array([[1,2,3]])
print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Exercise - Initialize array

In [39]:
arr = np.full((5,5), 0)
arr[(0,-1),:] = 1
arr[:,(0,-1)] = 1
arr[2,2] = 9
print(arr)

# Different solution - replacing the middle part
output=np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying arrays

In [42]:
# Pointing to single object
a = np.array([1,2,3])
b = a
print(a)
print(b)
b[0] = 100
print(a)
print(b)

# Creating a real copy
c = np.array([1,2,3])
d = c.copy()
print(c)
print(d)
d[0] = 100
print(c)
print(d)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]
[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


#### Mathematics

In [50]:
# Vectorized operations
a = np.array([1,2,3,4])
print(a)

print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

print(np.sin(a))
print(np.cos(a))

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [47]:
# Elementwise operations with multiple arrays
b = np.array([1,0,1,0])
print(b)

print(a + b)

[1 0 1 0]
[2 2 4 4]


#### Linear algebra

In [54]:
a = np.full((2,3), 1)
b = np.full((3,2), 2)
c = np.identity(3)
print(a)
print(b)

# Matrix multiplication
print(np.matmul(a,b))

# Matrix determinant
print(np.linalg.det(c))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]
1.0


#### Statistics

In [67]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

# From full array
print(np.min(a))
print(np.max(a))
print(np.sum(a))

# Looking at full rows
print(np.min(a, axis=0))
print(np.max(a, axis=0))
print(np.sum(a, axis=0))

[[1 2 3]
 [4 5 6]]
1
6
21
[1 2 3]
[4 5 6]
[5 7 9]


#### Reorganizing arrays

In [72]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [73]:
# Reshape matrix
after = before.reshape((8, 1))
print(after)
print(after.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


In [74]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [75]:
# Horiztonally stacking vectors
print(np.hstack([v1, v2]))

[1 2 3 4 5 6 7 8]


#### Load data from file

In [81]:
data = np.genfromtxt("data.txt", delimiter=",")
print(data)

data = data.astype("int32")
print(data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking and advanced indexing

In [82]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [92]:
(data > 50) & (data < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [83]:
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [86]:
# Indexing using lists
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [89]:
np.any(data > 50)

True

In [90]:
np.all(data > 50)

False

#### Exercise - Indexing

In [122]:
matrix = np.random.randint(0, 9, (6,5))
print(matrix)

print(matrix[2:4, 0:2])
print(matrix[[0,1,2,3], [1,2,3,4]])
print(matrix[[0,4,5], 3:])


[[5 8 0 8 1]
 [1 4 2 8 8]
 [6 5 1 7 5]
 [3 3 6 2 6]
 [4 7 3 0 1]
 [8 7 1 4 6]]
[[6 5]
 [3 3]]
[8 2 7 6]
[[8 1]
 [0 1]
 [4 6]]
